# Generated by Django 5.2.4 on 2025-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_region_remove_product_height_product_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='region_images/'),
        ),
    ]
