# Generated by Django 5.2.4 on 2025-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
